/**
 * ValidationProvenancePanel — real-outcome earned-tier evidence grades.
 *
 * Additive panel that displays, for every component of the Ovarian HGSOC Resistance &
 * Biomarker subsystem, the strongest HONEST earned tier derived from real, outcome-linked
 * patient cohorts (cBioPortal ov_tcga_pan_can_atlas_2018 n=585; GEO GSE63885 n=75), plus the
 * 5.3 model-calibration verdict and the two 5.1 gap closures (ctDNA wiring, KELIM Signal 6).
 *
 * Data source: /data/resistance_biomarker_provenance.json (canonical registry, generated by
 * api/services/resistance_prophet/provenance_registry.py). No component is labeled
 * "clinically validated"; tiers are the strongest honest evidence grade.
 */
import React, { useEffect, useState } from 'react';
import {
    Box, Paper, Typography, Chip, Table, TableBody, TableCell, TableContainer,
    TableHead, TableRow, Stack, Divider, Tooltip, Alert, CircularProgress,
} from '@mui/material';

// Phylo-consistent, colorblind-safe mapping of earned tier -> MUI color + hex.
const TIER_STYLE = {
    EXTERNALLY_VALIDATED_RUO: { color: 'success', hex: '#75A025', label: 'Externally validated (RUO)' },
    COHORT_VALIDATED_RUO: { color: 'success', hex: '#0279EE', label: 'Cohort validated (RUO)' },
    CALIBRATED_RUO: { color: 'info', hex: '#0279EE', label: 'Calibrated (RUO)' },
    CALIBRATED_RUO_BORDERLINE: { color: 'warning', hex: '#FF9400', label: 'Calibrated — borderline (CI passes, permutation n.s.)' },
    EXPRESSION_REPLICATES_DIRECTION_RUO: { color: 'info', hex: '#0279EE', label: 'Expression channel replicates direction (RUO)' },
    BORDERLINE_RUO: { color: 'warning', hex: '#FF9400', label: 'Borderline (underpowered)' },
    COHORT_TESTED_NULL: { color: 'default', hex: '#8a8a8a', label: 'Tested — no association' },
    LITERATURE_ONLY: { color: 'default', hex: '#b0b0b0', label: 'Literature only' },
    DISCOVERY_ONLY: { color: 'warning', hex: '#FF9400', label: 'Discovery only' },
    INSUFFICIENT_EVENTS: { color: 'default', hex: '#c0c0c0', label: 'Insufficient events' },
};

// Compact meta-analytic replication summary for a gene row (v2.0).
function fmtReplication(r) {
    const ext = r.external_replication || r.pooled_expr_os_retest;
    if (!ext || ext.pooled_HR_per_SD == null) return '—';
    const k = ext.n_independent_cohorts ?? ext.n_cohorts;
    const ci = ext.pooled_CI || [];
    return `${k} cohorts · pooled HR/SD ${ext.pooled_HR_per_SD} (95% CI ${ci[0]}–${ci[1]}), I²=${ext.I2_pct}%`;
}

// Survival outcome-validation summary for a gene row (v3.0): univariable Cox on OS,
// per-SD z-scored expression, DerSimonian–Laird meta across independent (non-TCGA) cohorts,
// BH-FDR corrected. Only rendered when the gene cleared the outcome-validation bar (q<0.05).
function fmtSurvivalOutcome(so) {
    if (!so || so.pooled_HR_per_SD == null) return '—';
    const ci = so.pooled_CI || [];
    const q = so.p_bh_fdr;
    const qStr = q != null ? (q < 1e-3 ? q.toExponential(1) : q.toFixed(4)) : 'NA';
    const c = so.mean_c_index != null ? `, C=${so.mean_c_index}` : '';
    return `OS HR/SD ${so.pooled_HR_per_SD} (95% CI ${ci[0]}–${ci[1]}), q=${qStr}, I²=${so.I2_pct}%, ${so.n_independent_cohorts} cohorts${c}`;
}

// Compact numeric formatter for display chips (3 significant decimals).
function fmt3(v) {
    if (v == null || Number.isNaN(Number(v))) return '—';
    return Number(v).toFixed(3);
}

function TierChip({ tier }) {
    const s = TIER_STYLE[tier] || { color: 'default', hex: '#c0c0c0', label: tier || 'Unknown' };
    return (
        <Tooltip title={s.label}>
            <Chip
                size="small"
                label={tier}
                sx={{ bgcolor: s.hex, color: '#fff', fontWeight: 600, fontSize: '0.68rem' }}
            />
        </Tooltip>
    );
}

function fmtHeadline(h) {
    if (!h) return '—';
    if (h.metric && h.value != null) {
        const ci = h.ci && h.ci[0] != null ? ` (95% CI ${h.ci[0]}–${h.ci[1]}${h.p != null ? `, p=${h.p}` : ''})` : '';
        const auroc = h.auroc != null ? `, AUROC ${h.auroc}` : '';
        return `${h.metric} ${h.value}${ci}${auroc}`;
    }
    return '—';
}

export default function ValidationProvenancePanel({ dataUrl = '/data/resistance_biomarker_provenance.json' }) {
    const [data, setData] = useState(null);
    const [err, setErr] = useState(null);

    useEffect(() => {
        let alive = true;
        fetch(dataUrl)
            .then((r) => {
                if (!r.ok) throw new Error(`HTTP ${r.status}`);
                return r.json();
            })
            .then((j) => { if (alive) setData(j); })
            .catch((e) => { if (alive) setErr(String(e)); });
        return () => { alive = false; };
    }, [dataUrl]);

    if (err) {
        return <Alert severity="warning">Validation provenance unavailable: {err}</Alert>;
    }
    if (!data) {
        return (
            <Box sx={{ display: 'flex', justifyContent: 'center', p: 3 }}>
                <CircularProgress size={24} />
            </Box>
        );
    }

    // Build display rows from genes_52 (registry) — sorted strongest-first.
    const RANK = {
        EXTERNALLY_VALIDATED_RUO: 7, COHORT_VALIDATED_RUO: 6, CALIBRATED_RUO: 5,
        CALIBRATED_RUO_BORDERLINE: 5, EXPRESSION_REPLICATES_DIRECTION_RUO: 5,
        BORDERLINE_RUO: 4, COHORT_TESTED_NULL: 3, LITERATURE_ONLY: 2, DISCOVERY_ONLY: 1,
        INSUFFICIENT_EVENTS: 0,
    };
    const genes = Object.entries(data.genes_52 || {})
        .map(([gene, r]) => ({ gene, ...r }))
        .sort((a, b) => (RANK[b.earned_tier] || 0) - (RANK[a.earned_tier] || 0));

    const m53 = (data.model_53 || {}).logit_resistance_probability || {};
    const m53v2 = (data.model_53_v2 || {}).logit_resistance_probability_expr || {};
    const gaps = data.gap_5_1 || {};

    // v3.0 outcome blocks (additive; render only when present in the registry payload).
    const m53v3 = data.model_53_v3 || null;
    const trackA = (m53v3 && (m53v3.track_A_survival_risk_score || m53v3.track_A)) || null;
    const trackB = (m53v3 && (m53v3.track_B_parsimonious_resistance_classifier
        || m53v3.track_B_parsimonious_binary_classifier || m53v3.track_B)) || null;
    const ctdna = data.ctdna_outcome || null;
    const ctdnaTF = ctdna && ctdna.cox_results ? {
        pfs: ctdna.cox_results.pfs?.tf, os: ctdna.cox_results.os?.tf,
    } : null;
    const plco = data.plco_outcome_context || null;
    const analytical = data.analytical_validation || null;
    const mfap4Cv = analytical?.mfap4_marker?.precision_by_normalization?.zscore?.cv_pct;
    const ctdnaCv = analytical?.ctdna_grouping?.precision?.tf_os_c_index?.cv_pct;

    const headlineFor = (r) => {
        if (r.os_HR != null && r.os_CI && r.os_CI[0] != null) {
            return `OS HR ${r.os_HR} (95% CI ${r.os_CI[0]}–${r.os_CI[1]}, p=${r.os_p})`;
        }
        if (r.expr_OR_per_SD != null) {
            const ci = r.expr_OR_CI || [];
            return `expr OR/SD ${r.expr_OR_per_SD} (95% CI ${ci[0]}–${ci[1]}, AUROC ${r.expr_AUROC}, p=${r.expr_p})`;
        }
        return '—';
    };

    return (
        <Paper elevation={2} sx={{ p: 2.5, borderRadius: 2 }}>
            <Typography variant="h6" sx={{ fontWeight: 700, mb: 0.5 }}>
                Real-Outcome Validation — Earned Evidence Grades
            </Typography>
            <Typography variant="caption" color="text.secondary">
                Cohorts: cBioPortal ov_tcga_pan_can_atlas_2018 (n=585, OS/PFS TCGA-CDR anchored) ·
                GEO GSE63885 (n=75, independent expression) · v3.0 survival outcome-validation across
                up to 28 curatedOvarianData serous cohorts (OS in ~3,300 patients; TCGA
                derivation-only, independent cohorts held-out) using per-SD Cox + DerSimonian–Laird
                random-effects meta-analysis with BH-FDR correction. Four markers
                (MFAP4, CCNE1, KRAS, BRCA2) are outcome-validated (q&lt;0.05). No component is labeled
                &ldquo;clinically validated&rdquo;; every tier is the strongest honest, Research-Use-Only
                evidence grade earned on retrospective public cohorts.
            </Typography>

            <TableContainer sx={{ mt: 2, maxHeight: 420 }}>
                <Table size="small" stickyHeader>
                    <TableHead>
                        <TableRow>
                            <TableCell sx={{ fontWeight: 700 }}>Gene</TableCell>
                            <TableCell sx={{ fontWeight: 700 }}>Earned tier</TableCell>
                            <TableCell sx={{ fontWeight: 700 }}>Real-outcome evidence</TableCell>
                            <TableCell sx={{ fontWeight: 700 }}>Outcome-validated survival (OS, meta)</TableCell>
                            <TableCell sx={{ fontWeight: 700 }}>External replication (meta)</TableCell>
                            <TableCell sx={{ fontWeight: 700 }} align="right">n exposed</TableCell>
                        </TableRow>
                    </TableHead>
                    <TableBody>
                        {genes.map((r) => (
                            <TableRow key={r.gene} hover>
                                <TableCell sx={{ fontWeight: 600 }}>{r.gene}</TableCell>
                                <TableCell><TierChip tier={r.earned_tier} /></TableCell>
                                <TableCell sx={{ fontSize: '0.78rem' }}>{headlineFor(r)}</TableCell>
                                <TableCell sx={{ fontSize: '0.76rem', fontWeight: (r.survival_outcome && String(r.survival_outcome.verdict || '').startsWith('OUTCOME_VALIDATED')) ? 700 : 400, color: (r.survival_outcome && r.survival_outcome.pooled_HR_per_SD != null) ? 'text.primary' : 'text.secondary' }}>{fmtSurvivalOutcome(r.survival_outcome)}</TableCell>
                                <TableCell sx={{ fontSize: '0.76rem', color: (r.external_replication || r.pooled_expr_os_retest) ? 'text.primary' : 'text.secondary' }}>{fmtReplication(r)}</TableCell>
                                <TableCell align="right">{r.n_exposed ?? '—'}</TableCell>
                            </TableRow>
                        ))}
                    </TableBody>
                </Table>
            </TableContainer>

            <Divider sx={{ my: 2 }} />

            <Typography variant="subtitle2" sx={{ fontWeight: 700 }}>
                5.3 Model calibration (logit resistance probability)
            </Typography>
            <Stack direction="row" spacing={1} sx={{ mt: 1, flexWrap: 'wrap', gap: 1 }}>
                <Chip size="small" sx={{ bgcolor: '#FF9400', color: '#fff', fontWeight: 600 }}
                    label="DISCOVERY_ONLY — NOT CALIBRATED" />
                {m53.prespecified_genomic_logit_TCGA && (
                    <Chip size="small" variant="outlined"
                        label={`OOF AUC ${m53.prespecified_genomic_logit_TCGA.oof_auc} (95% CI ${m53.prespecified_genomic_logit_TCGA.oof_auc_ci95?.[0]}–${m53.prespecified_genomic_logit_TCGA.oof_auc_ci95?.[1]})`} />
                )}
            </Stack>
            <Typography variant="caption" color="text.secondary" sx={{ display: 'block', mt: 1 }}>
                {m53.reason}
                {m53.refit_coefficients_real &&
                    ` Real refit (recorded, not shipped as validated): b_brca ${m53.refit_coefficients_real.b_brca}, b_mapk ${m53.refit_coefficients_real.b_mapk}.`}
            </Typography>
            {m53v2.oof_auc != null && (
                <Box sx={{ mt: 1.5 }}>
                    <Stack direction="row" spacing={1} sx={{ flexWrap: 'wrap', gap: 1 }}>
                        <Chip size="small" sx={{ bgcolor: '#FF9400', color: '#fff', fontWeight: 600 }}
                            label={m53v2.verdict} />
                        <Chip size="small" variant="outlined"
                            label={`v2 pooled expr model: OOF AUC ${m53v2.oof_auc} (95% CI ${m53v2.oof_auc_ci95?.[0]}–${m53v2.oof_auc_ci95?.[1]}), n=${m53v2.n}/${m53v2.events} events`} />
                        <Chip size="small" variant="outlined"
                            label={`permutation p=${m53v2.permutation_p}`} />
                    </Stack>
                    <Typography variant="caption" color="text.secondary" sx={{ display: 'block', mt: 1 }}>
                        {m53v2.honesty_statement}
                    </Typography>
                </Box>
            )}

            {m53v3 && (
                <Box sx={{ mt: 2 }}>
                    <Typography variant="subtitle2" sx={{ fontWeight: 700 }}>
                        5.3 v3 recalibration — survival risk score + parsimonious classifier
                    </Typography>
                    {trackA && (
                        <Stack direction="row" spacing={1} sx={{ mt: 1, flexWrap: 'wrap', gap: 1 }}>
                            <Chip size="small" sx={{ bgcolor: '#0279EE', color: '#fff', fontWeight: 600 }}
                                label="Track A — survival risk score" />
                            <Chip size="small" variant="outlined"
                                label={`held-out pooled C-index ${fmt3(trackA.pooled_c_index?.mean_c_index ?? trackA.pooled_c_index)} (95% CI ${fmt3((trackA.pooled_c_index?.ci || trackA.pooled_c_index_ci || [])[0])}–${fmt3((trackA.pooled_c_index?.ci || trackA.pooled_c_index_ci || [])[1])})`} />
                            <Chip size="small" variant="outlined"
                                label={`${trackA.pooled_c_index?.n_heldout_cohorts ?? trackA.n_heldout_cohorts ?? '9'} independent held-out cohorts`} />
                        </Stack>
                    )}
                    {trackB && (
                        <Stack direction="row" spacing={1} sx={{ mt: 1, flexWrap: 'wrap', gap: 1 }}>
                            <Chip size="small" sx={{ bgcolor: '#75A025', color: '#fff', fontWeight: 600 }}
                                label={trackB.verdict} />
                            <Chip size="small" variant="outlined"
                                label={`5-gene parsimonious: OOF AUC ${fmt3(trackB.oof_auc)} (95% CI ${fmt3((trackB.oof_auc_ci || [])[0])}–${fmt3((trackB.oof_auc_ci || [])[1])})`} />
                            <Chip size="small" variant="outlined"
                                label={`permutation p=${Number(trackB.permutation_p).toFixed(3)}, ${trackB.n_events} events`} />
                            {trackB.brier != null && (
                                <Chip size="small" variant="outlined" label={`Brier ${fmt3(trackB.brier)}`} />
                            )}
                        </Stack>
                    )}
                    <Typography variant="caption" color="text.secondary" sx={{ display: 'block', mt: 1 }}>
                        Track A: 14-gene multivariable Cox risk score derived on TCGA (LOCKED coefficients
                        + LOCKED tertile cutoffs), evaluated only on independent held-out cohorts.
                        Track B: parsimonious {Array.isArray(trackB?.feature_set) ? trackB.feature_set.join(' + ') : '5-gene'} binary
                        classifier, leave-one-cohort-out nested CV, locked 0.5 threshold — shrinking the
                        feature set to raise events-per-variable clears the internal calibration bar the
                        14-feature model missed. Thresholds are pre-specified and locked for evaluation,
                        not tied to a clinical decision. RUO.
                    </Typography>
                </Box>
            )}

            {ctdna && (
                <Box sx={{ mt: 2 }}>
                    <Typography variant="subtitle2" sx={{ fontWeight: 700 }}>
                        ctDNA outcome channel (prognostic-only)
                    </Typography>
                    <Stack direction="row" spacing={1} sx={{ mt: 1, flexWrap: 'wrap', gap: 1 }}>
                        <Chip size="small" sx={{ bgcolor: '#75A025', color: '#fff', fontWeight: 600 }}
                            label={ctdna.prognostic_channel_verdict || ctdna.verdict || 'OUTCOME_VALIDATED_PROGNOSTIC (RUO)'} />
                        {ctdnaTF && ctdnaTF.pfs && ctdnaTF.os && (
                            <Chip size="small" variant="outlined"
                                label={`TF · PFS HR/SD ${Number(ctdnaTF.pfs.hr_per_sd).toFixed(3)} (p=${Number(ctdnaTF.pfs.p).toExponential(1)}), OS HR/SD ${Number(ctdnaTF.os.hr_per_sd).toFixed(3)} (p=${Number(ctdnaTF.os.p).toFixed(3)})`} />
                        )}
                    </Stack>
                    <Typography variant="caption" color="text.secondary" sx={{ display: 'block', mt: 1 }}>
                        {ctdna.decision_scope || 'PROGNOSTIC ONLY — structurally excluded from resistance / routing; cutoffs exploratory; not clinically validated.'}
                        {ctdna.source ? ` Reference cohort: ${ctdna.source}.` : ''}
                    </Typography>
                </Box>
            )}

            {plco && (
                <Box sx={{ mt: 2 }}>
                    <Typography variant="subtitle2" sx={{ fontWeight: 700 }}>
                        PLCO CA-125 kinetics — outcome context (screening cohort)
                    </Typography>
                    <Stack direction="row" spacing={1} sx={{ mt: 1, flexWrap: 'wrap', gap: 1 }}>
                        <Chip size="small" sx={{ bgcolor: '#8a8a8a', color: '#fff', fontWeight: 600 }}
                            label="OUTCOME_CONTEXT_NULL_RUO" />
                        <Chip size="small" variant="outlined"
                            label={`incident-cancer screening AUROC ${plco.screening_anchor_unchanged?.log_slope_auroc_incident_cancer ?? '0.652'} (unchanged)`} />
                    </Stack>
                    <Typography variant="caption" color="text.secondary" sx={{ display: 'block', mt: 1 }}>
                        Directly tested whether pre-diagnosis CA-125 kinetics predict stage-at-diagnosis
                        (AUROC {plco.analysis_1_stage?.auroc_advanced_by_logslope ?? '0.531'}, p={plco.analysis_1_stage?.mwu_p != null ? Number(plco.analysis_1_stage.mwu_p).toFixed(2) : '0.52'})
                        and post-diagnosis survival (Cox HR/SD {plco.analysis_2_survival_after_dx?.cox_HR_per_SD_logslope ?? '1.06'}, p={plco.analysis_2_survival_after_dx?.p != null ? Number(plco.analysis_2_survival_after_dx.p).toFixed(2) : '0.42'}).
                        Both null — a screening early-signal method does not transfer to a
                        treatment-resistance / outcome predictor. Screening anchor unchanged. RUO.
                    </Typography>
                </Box>
            )}

            {analytical && (
                <Box sx={{ mt: 2 }}>
                    <Typography variant="subtitle2" sx={{ fontWeight: 700 }}>
                        In-silico analytical validation
                    </Typography>
                    <Typography variant="caption" color="text.secondary" sx={{ display: 'block', mt: 0.5 }}>
                        {analytical.disclaimer || 'IN-SILICO analytical validation (precision / reproducibility / robustness analogs). NOT wet-lab analytical validation (LoD/LoQ/precision) under a quality system. RUO.'}
                        {mfap4Cv != null ? ` MFAP4 C-index precision CV%=${Number(mfap4Cv).toFixed(1)} (20 seeds × 2 normalizations).` : ''}
                        {ctdnaCv != null ? ` ctDNA TF C-index precision CV%=${Number(ctdnaCv).toFixed(1)}.` : ''}
                    </Typography>
                </Box>
            )}

            <Divider sx={{ my: 2 }} />

            <Typography variant="subtitle2" sx={{ fontWeight: 700 }}>
                5.1 Gap closures
            </Typography>
            <Stack spacing={0.5} sx={{ mt: 1 }}>
                <Box>
                    <Chip size="small" sx={{ bgcolor: '#75A025', color: '#fff', fontWeight: 600, mr: 1 }}
                        label="ctDNA (RES-OV-P0-006)" />
                    <Typography variant="caption" color="text.secondary">
                        {gaps['RES-OV-P0-006_ctdna']?.status}
                    </Typography>
                </Box>
                <Box>
                    <Chip size="small" sx={{ bgcolor: '#75A025', color: '#fff', fontWeight: 600, mr: 1 }}
                        label="KELIM Signal 6 (RES-OV-P0-009)" />
                    <Typography variant="caption" color="text.secondary">
                        {gaps['RES-OV-P0-009_kelim_signal6']?.status}
                    </Typography>
                </Box>
            </Stack>
        </Paper>
    );
}
