/**
 * ValidationProvenancePanel — real-outcome earned-tier evidence grades.
 *
 * Additive panel that displays, for every component of the Ovarian HGSOC Resistance &
 * Biomarker subsystem, the strongest HONEST earned tier derived from real, outcome-linked
 * patient cohorts (cBioPortal ov_tcga_pan_can_atlas_2018 n=585; GEO GSE63885 n=75), plus the
 * 5.3 model-calibration verdict and the two 5.1 gap closures (ctDNA wiring, KELIM Signal 6).
 *
 * Data source: /data/resistance_biomarker_provenance.json (canonical registry, generated by
 * api/services/resistance_prophet/provenance_registry.py). No component is labeled
 * "clinically validated"; tiers are the strongest honest evidence grade.
 */
import React, { useEffect, useState } from 'react';
import {
    Box, Paper, Typography, Chip, Table, TableBody, TableCell, TableContainer,
    TableHead, TableRow, Stack, Divider, Tooltip, Alert, CircularProgress,
} from '@mui/material';

// Phylo-consistent, colorblind-safe mapping of earned tier -> MUI color + hex.
const TIER_STYLE = {
    EXTERNALLY_VALIDATED_RUO: { color: 'success', hex: '#75A025', label: 'Externally validated (RUO)' },
    COHORT_VALIDATED_RUO: { color: 'success', hex: '#0279EE', label: 'Cohort validated (RUO)' },
    CALIBRATED_RUO: { color: 'info', hex: '#0279EE', label: 'Calibrated (RUO)' },
    CALIBRATED_RUO_BORDERLINE: { color: 'warning', hex: '#FF9400', label: 'Calibrated — borderline (CI passes, permutation n.s.)' },
    EXPRESSION_REPLICATES_DIRECTION_RUO: { color: 'info', hex: '#0279EE', label: 'Expression channel replicates direction (RUO)' },
    BORDERLINE_RUO: { color: 'warning', hex: '#FF9400', label: 'Borderline (underpowered)' },
    COHORT_TESTED_NULL: { color: 'default', hex: '#8a8a8a', label: 'Tested — no association' },
    LITERATURE_ONLY: { color: 'default', hex: '#b0b0b0', label: 'Literature only' },
    DISCOVERY_ONLY: { color: 'warning', hex: '#FF9400', label: 'Discovery only' },
    INSUFFICIENT_EVENTS: { color: 'default', hex: '#c0c0c0', label: 'Insufficient events' },
};

// Compact meta-analytic replication summary for a gene row (v2.0).
function fmtReplication(r) {
    const ext = r.external_replication || r.pooled_expr_os_retest;
    if (!ext || ext.pooled_HR_per_SD == null) return '—';
    const k = ext.n_independent_cohorts ?? ext.n_cohorts;
    const ci = ext.pooled_CI || [];
    return `${k} cohorts · pooled HR/SD ${ext.pooled_HR_per_SD} (95% CI ${ci[0]}–${ci[1]}), I²=${ext.I2_pct}%`;
}

function TierChip({ tier }) {
    const s = TIER_STYLE[tier] || { color: 'default', hex: '#c0c0c0', label: tier || 'Unknown' };
    return (
        <Tooltip title={s.label}>
            <Chip
                size="small"
                label={tier}
                sx={{ bgcolor: s.hex, color: '#fff', fontWeight: 600, fontSize: '0.68rem' }}
            />
        </Tooltip>
    );
}

function fmtHeadline(h) {
    if (!h) return '—';
    if (h.metric && h.value != null) {
        const ci = h.ci && h.ci[0] != null ? ` (95% CI ${h.ci[0]}–${h.ci[1]}${h.p != null ? `, p=${h.p}` : ''})` : '';
        const auroc = h.auroc != null ? `, AUROC ${h.auroc}` : '';
        return `${h.metric} ${h.value}${ci}${auroc}`;
    }
    return '—';
}

export default function ValidationProvenancePanel({ dataUrl = '/data/resistance_biomarker_provenance.json' }) {
    const [data, setData] = useState(null);
    const [err, setErr] = useState(null);

    useEffect(() => {
        let alive = true;
        fetch(dataUrl)
            .then((r) => {
                if (!r.ok) throw new Error(`HTTP ${r.status}`);
                return r.json();
            })
            .then((j) => { if (alive) setData(j); })
            .catch((e) => { if (alive) setErr(String(e)); });
        return () => { alive = false; };
    }, [dataUrl]);

    if (err) {
        return <Alert severity="warning">Validation provenance unavailable: {err}</Alert>;
    }
    if (!data) {
        return (
            <Box sx={{ display: 'flex', justifyContent: 'center', p: 3 }}>
                <CircularProgress size={24} />
            </Box>
        );
    }

    // Build display rows from genes_52 (registry) — sorted strongest-first.
    const RANK = {
        EXTERNALLY_VALIDATED_RUO: 7, COHORT_VALIDATED_RUO: 6, CALIBRATED_RUO: 5,
        CALIBRATED_RUO_BORDERLINE: 5, EXPRESSION_REPLICATES_DIRECTION_RUO: 5,
        BORDERLINE_RUO: 4, COHORT_TESTED_NULL: 3, LITERATURE_ONLY: 2, DISCOVERY_ONLY: 1,
        INSUFFICIENT_EVENTS: 0,
    };
    const genes = Object.entries(data.genes_52 || {})
        .map(([gene, r]) => ({ gene, ...r }))
        .sort((a, b) => (RANK[b.earned_tier] || 0) - (RANK[a.earned_tier] || 0));

    const m53 = (data.model_53 || {}).logit_resistance_probability || {};
    const m53v2 = (data.model_53_v2 || {}).logit_resistance_probability_expr || {};
    const gaps = data.gap_5_1 || {};

    const headlineFor = (r) => {
        if (r.os_HR != null && r.os_CI && r.os_CI[0] != null) {
            return `OS HR ${r.os_HR} (95% CI ${r.os_CI[0]}–${r.os_CI[1]}, p=${r.os_p})`;
        }
        if (r.expr_OR_per_SD != null) {
            const ci = r.expr_OR_CI || [];
            return `expr OR/SD ${r.expr_OR_per_SD} (95% CI ${ci[0]}–${ci[1]}, AUROC ${r.expr_AUROC}, p=${r.expr_p})`;
        }
        return '—';
    };

    return (
        <Paper elevation={2} sx={{ p: 2.5, borderRadius: 2 }}>
            <Typography variant="h6" sx={{ fontWeight: 700, mb: 0.5 }}>
                Real-Outcome Validation — Earned Evidence Grades
            </Typography>
            <Typography variant="caption" color="text.secondary">
                Cohorts: cBioPortal ov_tcga_pan_can_atlas_2018 (n=585, OS/PFS TCGA-CDR anchored) ·
                GEO GSE63885 (n=75, independent expression) · v2.0 external replication across up to
                17 independent curatedOvarianData HGSOC cohorts (~3,000 patients, DerSimonian–Laird
                random-effects meta-analysis). No component is labeled &ldquo;clinically
                validated&rdquo;; tiers are the strongest honest evidence grade.
            </Typography>

            <TableContainer sx={{ mt: 2, maxHeight: 420 }}>
                <Table size="small" stickyHeader>
                    <TableHead>
                        <TableRow>
                            <TableCell sx={{ fontWeight: 700 }}>Gene</TableCell>
                            <TableCell sx={{ fontWeight: 700 }}>Earned tier</TableCell>
                            <TableCell sx={{ fontWeight: 700 }}>Real-outcome evidence</TableCell>
                            <TableCell sx={{ fontWeight: 700 }}>External replication (meta)</TableCell>
                            <TableCell sx={{ fontWeight: 700 }} align="right">n exposed</TableCell>
                        </TableRow>
                    </TableHead>
                    <TableBody>
                        {genes.map((r) => (
                            <TableRow key={r.gene} hover>
                                <TableCell sx={{ fontWeight: 600 }}>{r.gene}</TableCell>
                                <TableCell><TierChip tier={r.earned_tier} /></TableCell>
                                <TableCell sx={{ fontSize: '0.78rem' }}>{headlineFor(r)}</TableCell>
                                <TableCell sx={{ fontSize: '0.76rem', color: (r.external_replication || r.pooled_expr_os_retest) ? 'text.primary' : 'text.secondary' }}>{fmtReplication(r)}</TableCell>
                                <TableCell align="right">{r.n_exposed ?? '—'}</TableCell>
                            </TableRow>
                        ))}
                    </TableBody>
                </Table>
            </TableContainer>

            <Divider sx={{ my: 2 }} />

            <Typography variant="subtitle2" sx={{ fontWeight: 700 }}>
                5.3 Model calibration (logit resistance probability)
            </Typography>
            <Stack direction="row" spacing={1} sx={{ mt: 1, flexWrap: 'wrap', gap: 1 }}>
                <Chip size="small" sx={{ bgcolor: '#FF9400', color: '#fff', fontWeight: 600 }}
                    label="DISCOVERY_ONLY — NOT CALIBRATED" />
                {m53.prespecified_genomic_logit_TCGA && (
                    <Chip size="small" variant="outlined"
                        label={`OOF AUC ${m53.prespecified_genomic_logit_TCGA.oof_auc} (95% CI ${m53.prespecified_genomic_logit_TCGA.oof_auc_ci95?.[0]}–${m53.prespecified_genomic_logit_TCGA.oof_auc_ci95?.[1]})`} />
                )}
            </Stack>
            <Typography variant="caption" color="text.secondary" sx={{ display: 'block', mt: 1 }}>
                {m53.reason}
                {m53.refit_coefficients_real &&
                    ` Real refit (recorded, not shipped as validated): b_brca ${m53.refit_coefficients_real.b_brca}, b_mapk ${m53.refit_coefficients_real.b_mapk}.`}
            </Typography>
            {m53v2.oof_auc != null && (
                <Box sx={{ mt: 1.5 }}>
                    <Stack direction="row" spacing={1} sx={{ flexWrap: 'wrap', gap: 1 }}>
                        <Chip size="small" sx={{ bgcolor: '#FF9400', color: '#fff', fontWeight: 600 }}
                            label={m53v2.verdict} />
                        <Chip size="small" variant="outlined"
                            label={`v2 pooled expr model: OOF AUC ${m53v2.oof_auc} (95% CI ${m53v2.oof_auc_ci95?.[0]}–${m53v2.oof_auc_ci95?.[1]}), n=${m53v2.n}/${m53v2.events} events`} />
                        <Chip size="small" variant="outlined"
                            label={`permutation p=${m53v2.permutation_p}`} />
                    </Stack>
                    <Typography variant="caption" color="text.secondary" sx={{ display: 'block', mt: 1 }}>
                        {m53v2.honesty_statement}
                    </Typography>
                </Box>
            )}

            <Divider sx={{ my: 2 }} />

            <Typography variant="subtitle2" sx={{ fontWeight: 700 }}>
                5.1 Gap closures
            </Typography>
            <Stack spacing={0.5} sx={{ mt: 1 }}>
                <Box>
                    <Chip size="small" sx={{ bgcolor: '#75A025', color: '#fff', fontWeight: 600, mr: 1 }}
                        label="ctDNA (RES-OV-P0-006)" />
                    <Typography variant="caption" color="text.secondary">
                        {gaps['RES-OV-P0-006_ctdna']?.status}
                    </Typography>
                </Box>
                <Box>
                    <Chip size="small" sx={{ bgcolor: '#75A025', color: '#fff', fontWeight: 600, mr: 1 }}
                        label="KELIM Signal 6 (RES-OV-P0-009)" />
                    <Typography variant="caption" color="text.secondary">
                        {gaps['RES-OV-P0-009_kelim_signal6']?.status}
                    </Typography>
                </Box>
            </Stack>
        </Paper>
    );
}
